#!/bin/sh

. ./OPTIONS.sh

#RSYNCSOURCE=rsync://releases.ubuntu.com
RSYNCSOURCE=rsync://www.kernel.org/all
BASEDIR=${MIRRORDIR}/kernel

rsync --recursive --times --links --hard-links \
      --stats \
      -P \
      ${RSYNCSOURCE} ${BASEDIR} | tee -a ~/rsync.log
