#!/bin/sh

RSYNCSOURCE=rsync://rsync.gtlib.gatech.edu/archlinux/
BASEDIR=${MIRRORDIR}/archlinux

rsync -rtlvH --delete-after --delay-updates --safe-links --max-delete=1000 \
    ${RSYNCSOURCE} ${BASEDIR}
