#!/bin/sh

RSYNCSOURCE=rsync://mirrors.kernel.org/archlinux/
BASEDIR=${MIRRORDIR}/archlinux

rsync -rtlvH --delete-after --delay-updates --safe-links --max-delete=1000 \
    ${RSYNCSOURCE} ${BASEDIR}
