#!/bin/sh

RSYNCSOURCE=rsync://www.cygwin.com/cygwin-ftp
BASEDIR=${MIRRORDIR}/cygwin

rsync --recursive --times --links --hard-links \
      --stats --delete \
      --exclude ".description" --exclude ".schedule" \
      ${RSYNCSOURCE} ${BASEDIR}
