#!/bin/sh

#RSYNCSOURCE=rsync://download.wpi.edu:874/fedora-epel
#RSYNCSOURCE=rsync://rsync.gtlib.gatech.edu/fedora-epel
#RSYNCSOURCE=rsync://download-i2.fedoraproject.org/fedora-epel0
RSYNCSOURCE=rsync://mirrors.rit.edu/fedora-enchilada/epel/
BASEDIR=${MIRRORDIR}/epel

rsync -vaH --numeric-ids --delete --delete-after \
     --delay-updates \
    ${RSYNCSOURCE} ${BASEDIR}
