#!/bin/bash

set -e

# This script serves to sync the following modules from fedora-buffet:
# - fedora -> ${MIRRORDIR}/fedora
# - epel   -> ${MIRRORDIR}/epel

# To make quick-fedora-mirror happy, it does so through a bind mount,
# separate from the symlink farm at ${MIRRORDIR}.

# mirrors.mit.edu is on the IP ACL for fedora-buffet0 here
# so we'll use it. Adjust these values if switching upstreams.
#RSYNCSOURCE=rsync://download-i2.fedoraproject.org
RSYNCSOURCE=rsync://dl.fedoraproject.org
MASTERMODULE=fedora-buffet0
PREBITFLIP=1

TIMEFILE="${MIRRORDIR}/.locks/fedora-buffet.timefile"
QFM="./tools/fedora/quick-fedora-mirror"

if ! [ -x "${QFM}" ]; then
    # It is expected that this script is sourced by fetch-hudson
    # and that cwd is the workspace where the root of this repository
    # is checked out.
    echo "Could not find quick-fedora-mirror."
    exit 1
fi

# Early ownership checks for bind-mounted target directories.
exit_early=
for dir in epel fedora; do
    check_target="${MIRRORDIR}/fedora-buffet/${dir}"
    if ! [ -O "${check_target}" ]; then
        echo "${check_target} ownership is wrong; is the bind mount missing?"
        exit_early=yes
    fi
done
if [ -n "${exit_early}" ]; then
    exit 1
fi

exittrap() { :; }
trap 'exittrap' EXIT

TMPDIR=$(mktemp -d /tmp/fedora-buffet.XXXXXX) || die "Unable to mktemp"
exittrap() { rm -rf "${TMPDIR}"; }

CONF="${TMPDIR}/qfm.conf"
cat >"${CONF}" <<EOF
# This will be sourced by qfm, which uses zsh.
# Where our mirrors live
DESTD=${MIRRORDIR}/fedora-buffet
# State regarding last sync, and also a lockfile for qfm
TIMEFILE=${TIMEFILE}
# Upstream mirror that contains MASTERMODULE
REMOTE=${RSYNCSOURCE}
MASTERMODULE=${MASTERMODULE}
PREBITFLIP=${PREBITFLIP}
# Which module to sync
MODULES=(fedora epel)
# Map from module to location in DESTD
MODULEMAPPING=(fedora fedora epel epel)
# Add --progress to rsync
VERBOSE=7
TMPDIR=${TMPDIR}
EOF

"${QFM}" --config "${CONF}" --alwayscheck

rm -rf "${TMPDIR}"
exittrap() { :; }
