#!/bin/sh

RSYNCSOURCE=rsync://releases.finnix.org/finnix-releases/
BASEDIR=${MIRRORDIR}/finnix/releases
HOST=mirrors.mit.edu

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose --timeout=600 \
      --exclude="project/trace/${HOST}" \
      ${RSYNCSOURCE} ${BASEDIR}

mkdir -pv "${BASEDIR}/project/trace"
TZ=UTC date > "${BASEDIR}/project/trace/${HOST}"
