#!/bin/sh

RSYNCSOURCE=rsync://ftp11.us.FreeBSD.org/FreeBSD
BASEDIR=${MIRRORDIR}/FreeBSD

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose \
      --perms \
      -D \
      --delete \
      --exclude="Attic" \
      --timeout=300 \
	--size-only -z \
      ${RSYNCSOURCE} ${BASEDIR}
