#!/bin/sh

RSYNCSOURCE=ftp3.us.FreeBSD.org::FreeBSD/ 
BASEDIR=${MIRRORDIR}/FreeBSD

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose \
      --perms \
      -D \
      --delete \
      --timeout=300 \
      ${RSYNCSOURCE} ${BASEDIR}
