#!/bin/sh
# Modified from http://www.gentoo.org/doc/en/rsync.xml#doc_chap3

RSYNCSOURCE=rsync://masterdistfiles.gentoo.org/gentoo
BASEDIR=${MIRRORDIR}/gentoo-distfiles

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose \
      --perms \
      -D \
      --delete \
      --timeout=300 \
      --exclude=releases/.test/THIS-FILE-SHOULD-NOT-BE-PUBLIC.txt \
      ${RSYNCSOURCE} ${BASEDIR}
