#!/bin/sh
# Modified from http://www.gentoo.org/doc/en/rsync.xml#doc_chap3

RSYNCSOURCE=rsync://ftp.ussg.iu.edu/gentoo-distfiles
BASEDIR=${MIRRORDIR}/gentoo-distfiles

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose \
      --perms \
      -D \
      --delete \
      --timeout=300 \
      ${RSYNCSOURCE} ${BASEDIR}
