#!/bin/sh

RSYNCSOURCE=rsync://us.archive.gnewsense.org/gnewsense
BASEDIR=${MIRRORDIR}/gnewsense

rsync -rlt -vL --delete --stats ${RSYNCSOURCE} ${BASEDIR}
#rsync -avL --delete --delete-before ${RSYNCSOURCE} ${BASEDIR}
