#!/bin/sh

RSYNCSOURCE=rsync://www.kernel.org/all
BASEDIR=${MIRRORDIR}/kernel

rsync --recursive --times --links --hard-links \
      --delete \
      --stats \
      --verbose \
      ${RSYNCSOURCE} ${BASEDIR}
