#!/bin/sh

RSYNCSOURCE=rsync://rsync.kernel.org/pub
BASEDIR=${MIRRORDIR}/kernel

rsync --recursive --times --links --hard-links \
      --delete \
      --stats \
      --verbose \
      ${RSYNCSOURCE} ${BASEDIR}
