#!/bin/sh

RSYNCSOURCE="rsync://rsync-origin.macports.org"
BASEDIR="$MIRRORDIR/macports"

RSYNC_MODULES="packages distfiles release trunk"

RSYNC_ARGS="--compress --delete-delay --hard-links --links --no-motd --perms --recursive --stats --timeout=600 --times"

for RSYNC_MODULE in $RSYNC_MODULES; do
    RSYNC_URL="${RSYNCSOURCE}/${RSYNC_MODULE}"
    echo "Syncing $RSYNC_MODULE from $RSYNC_URL"
    mkdir -p "${BASEDIR}/${RSYNC_MODULE}"
    rsync $RSYNC_ARGS "$RSYNC_URL" "$BASEDIR/$RSYNC_MODULE"
    echo
done

