#!/bin/sh

RSYNCSOURCE=rsync://mirrors.nycbug.org/OpenBSD
BASEDIR=${MIRRORDIR}/pub/OpenBSD

mkdir -p ${BASEDIR}
rsync --archive --delete --stats --verbose \
       --exclude='/timestamp' \
       --exclude='.~tmp~' \
       ${RSYNCSOURCE} ${BASEDIR}
date +%s > ${BASEDIR}/timestamp
