#!/bin/sh

RSYNCSOURCE=rsync://openbsd.cs.toronto.edu/openbsd
BASEDIR=${MIRRORDIR}/pub/OpenBSD

mkdir -p ${BASEDIR}
rsync --archive --delete --stats --verbose \
       --exclude='.~tmp~' \
       ${RSYNCSOURCE} ${BASEDIR}
