#!/bin/sh
#Requested in an email forwarded to mirrors@ by tibbets on 10/22

RSYNCSOURCE=rsync://sunjammer.sugarlabs.org/pub
BASEDIR=${MIRRORDIR}/sugarlabs

rsync -avzL --delete --exclude=soas/snapshots ${RSYNCSOURCE} ${BASEDIR}
