#!/bin/sh
#Requested in an email forwarded to mirrors@ by tibbets on 10/22

RSYNCSOURCE=rsync://sunjammer.sugarlabs.org/pub
BASEDIR=${MIRRORDIR}/sugarlabs

rsync --recursive --times --links --hard-links \
      --stats --delete --delete-after \
      --verbose --timeout=600 \
      --exclude=soas/snapshots \
      ${RSYNCSOURCE} ${BASEDIR}
