#!/bin/sh

RSYNCSOURCE=rsync.torproject.org::amnesia-archive/tails
BASEDIR=${MIRRORDIR}/tails

rsync --recursive --times --links \
      --delete --delete-after \
      --stats --verbose \
      ${RSYNCSOURCE} ${BASEDIR}
