#!/bin/sh

RSYNCSOURCE=rsync://archive.ubuntu.com/ubuntu
#RSYNCSOURCE=rsync://ubuntu.media.mit.edu/ubuntu
BASEDIR=${MIRRORDIR}/ubuntu

rsync --recursive --times --links --hard-links \
      --stats \
      --verbose \
      --exclude "Packages*" --exclude "Sources*" \
      --exclude "Release*" \
      ${RSYNCSOURCE} ${BASEDIR}

rsync --recursive --times --links --hard-links \
      --stats --delete --delete-after \
      --verbose \
      --exclude "project/trace/${HOSTNAME}" \
      ${RSYNCSOURCE} ${BASEDIR}
