#!/bin/sh

RSYNCSOURCE=rsync://releases.ubuntu.com/releases
#RSYNCSOURCE=rsync://ubuntu.media.mit.edu/ubuntu-releases
BASEDIR=${MIRRORDIR}/ubuntu-releases

rsync --recursive --times --links --hard-links \
      --stats \
      -P \
      --exclude "Packages*" --exclude "Sources*" \
      --exclude "Release*" \
      ${RSYNCSOURCE} ${BASEDIR}

rsync --recursive --times --links --hard-links \
      --stats --delete --delete-after \
      -P \
      --exclude "project/trace/${HOSTNAME}" \
      ${RSYNCSOURCE} ${BASEDIR}