#!/bin/sh

RSYNCSOURCE=rsync://rsync.cdimage.ubuntu.com/cdimage
#RSYNCSOURCE=rsync://ubuntu.media.mit.edu/ubuntu-releases
BASEDIR=${MIRRORDIR}/ubuntu-cdimage

rsync --recursive --times --links --hard-links \
      --stats --delete --delete-after \
      --verbose \
			-D \
      ${RSYNCSOURCE} ${BASEDIR}
